#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=sperwin_mem_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=08:00:00
#SBATCH --output=slurm/mem_test.%A.%N.out

source erwin/bin/activate

cd experiments

uv run train_shapenet.py \
    --lr 5e-4 \
    --num-epochs 100000 \
    --data-path "/scratch-shared/scur2588/data/mlcfd_data/preprocessed" \
    --use-wandb \
    --batch-size 2 \
    --nsa-type NSAMSA \
    --experiment NSALastPytorch2_5e4