#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=erwinSN
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:30:00
#SBATCH --output=slurm/erwinshapenet.%A.%N.out

source erwin/bin/activate

cd experiments

uv run train_shapenet.py --num-epochs 200 --lr 1e-3 \
 --data-path "/scratch-shared/scur2588/data/mlcfd_data/preprocessed" \
 --nsa-type NSAMSA --size small --experiment NSAMSA_triton_shapenet_medium_200_test