#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=erwinOGSN
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:45:00
#SBATCH --output=slurm/mem_test.%A.%N.out

source erwin/bin/activate

cd experiments

uv run train_shapenet.py --num-epochs 10 --lr 1e-3 --data-path "/scratch-shared/scur2588/data/mlcfd_data/preprocessed" --use-wandb 1 --test 1 --msa-type BallMSA