#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=erwinSN
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=02:00:00
#SBATCH --output=slurm/erwinshapenet.%A.%N.out

source erwin/bin/activate

cd experiments

uv run train_shapenet.py --num-epochs 15000 --lr 1e-3 --use-wandb --test \
 --data-path "/scratch-shared/scur2588/data/mlcfd_data/preprocessed" \
 --config configs/erwin_mediumconfig_shapenet_minus2layers.yaml \
 --experiment shapenet_medium_baseline_minus2layers_15k