#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=erwinSN
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=05:00:00
#SBATCH --output=slurm/erwinshapenet.%A.%N.out

source erwin/bin/activate

cd experiments

uv run train_shapenet.py --num-epochs 100000 --lr 1e-3 --use-wandb --test \
 --data-path "/scratch-shared/scur2588/data/mlcfd_data/preprocessed" \
 --nsa-type NSAMSA_triton --size medium --experiment "fp32_test"