#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=fullattn
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=09:00:00
#SBATCH --output=slurm/erwinshapenet_fullattn.%A.%N.out

source erwin/bin/activate

cd experiments

uv run train_shapenet.py --num-epochs 40000 --lr 1e-3 --use-wandb --test \
 --data-path "/scratch-shared/scur2588/data/mlcfd_data/preprocessed" \
 --nsa-type FullAttention --nsa-loc begin --size medium  --experiment full_attention