#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=erwinSN
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=08:00:00
#SBATCH --output=slurm/nsa_loc_test.%A.%N.out

source erwin/bin/activate

cd experiments

uv run train_shapenet.py --num-epochs 100 --lr 1e-3 \
 --data-path "/scratch-shared/scur2588/data/mlcfd_data/preprocessed" \
 --nsa-type NSAMSA_triton --size medium --nsa-loc "[3, 4, -1]"