#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=beginsperwin_mem_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=01:30:00
#SBATCH --output=slurm/mem_test.%A.%N.out

source erwin/bin/activate

cd experiments

uv run test_shapenet.py \
    --num-epochs 100000 \
    --data-path "/scratch-shared/scur2588/data/mlcfd_data/preprocessed" \
    --use-wandb 1 \
    --test 1 \
    --batch-size 2 \
    --msa-type BallMSA \
    --experiment NSABeginPytorchfullmain \
    --beginnsa